version: "3"

services:

   springboot:
      build: ./build-java
      image: springboot:1.0_lenovo
      container_name: lenovo-springboot
      ports:
         - 8081:8081
      volumes:
         - "${JAVA_DIR}/target:/target"
      depends_on:
         - mysql
      links:
         - mysql

   mysql:
      build: ./build-mysql
      restart: always
      image: mysql:1.0_lenovo
      container_name: lenovo-mysql
      # ports:
      #    - 3306:3306
      environment: 
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${MYSQL_DATABASE}
      volumes:
         - "${MYSQL_DIR}/conf.d:/etc/mysql/conf.d"
         # - "${MYSQL_DIR}/logs:/var/log/mysql"
         - "${MYSQL_DIR}/data:/var/lib/mysql"

   nginx:
      restart: always
      image: nginx
      container_name: lenovo-nginx
      ports:
         - 80:80
      volumes:
         # - "${NGINX_DIR}/nginx.conf:/etc/nginx/nginx.conf"
         - "${NGINX_DIR}/conf.d:/etc/nginx/conf.d"
         # - "${NGINX_DIR}/log:/var/log/nginx"
         - "${NGINX_DIR}/dist:/usr/share/nginx/html"
      depends_on:
         - springboot
      links:
         - springboot